### ISSUE TITLE
Image naming convention and migration to github container registry

### ISSUE THREAD

**Issue by mhwasil** [b-it-bots/docker#20]
I am wondering why the naming of the bitbots image is bitbots/bitbots-{package}, I feel like it's a bit redundancy.
wouldn't it be better if we remove `bitbots` from the image name, for example `bitbots/industrial:{tag}`, `bitbots/domestic:{tag}, `bitbots/navigation:{tag}`. @argenos 

Currently there is no way to use old images because the tag is static based the ros distribution.
I am proposing new way of naming and tagging the image, which is based on `commit id` or commit `hash`:
* `bitbots/industrial-kinetic:{tag}` 
* `bitbots/domestic-kinetic:{tag}`
this approach is used in some big projects like jupyter.
and it's very useful when we want to go back to previous versions

@sthoduka @alex-mitrevski

**Comment by argenos** [comment]
In Dockerhub the part before the slash is actually the organization. The name of the image is just `bitbots-industral:{tag}`.

**Comment by argenos** [comment]
Since you are thinking about refactoring, I would also consider switching from Docker hub to GitHub packages.

**Comment by argenos** [comment]
> Currently there is no way to use old images because the tag is static based the ros distribution. 
> I am proposing new way of naming and tagging the image, which is based on commit id or commit hash:

That is usually how it should work, I think based on a commit hash is too fine-grained and you might run into data limits with Docker hub or GitHub packages. The initial idea was to generate images based on the branch (not the distribution) and for each tag (git tag, i.e. release).

**Comment by mhwasil** [comment]
Github packages is not free.. :-D.. 
but docker hub is free, but there is new retention policy now which limits unauthenticated users up to 100 pulls every 6H.

**Comment by argenos** [comment]
We have some benefits in GitHub based on our education status. From their pricing page, we are in the "Pro" category, which might not be enough given that the images we produce are not being optimized (and is something you might want to consider too), but it is usable see e.g. https://github.com/orgs/HBRS-SDP/packages

**Comment by mhwasil** [comment]
Yes, that's I  mean, since bitbots is already the name of the organization, why do we need to name the image with `bitbots` again?
either way is fine for me, it's just a bit redundancy.

What I am thinking was the tag, which would be nice if we can go back to the previous working version if something goes wrong.

> In Dockerhub the part before the slash is actually the organization. The name of the image is just bitbots-industral:{tag}

**Comment by argenos** [comment]
> Yes, that's I mean, since bitbots is already the name of the organization, why do we need to name the image with bitbots again?

When I originally created those images, I believe that that was the naming convention being used by other repositories. I could be mis-remembering. They were also originally hosted in my personal account `argenos/bitbots-domestic` where the naming convention maybe made more sense. It's all a matter of preference in the end, if most want to change the names I have no strong preference either.

> What I am thinking was the tag, which would be nice if we can go back to the previous working version if something goes wrong.

IMO this is what semantic versioning should be used for, not the commit hashes.

**Comment by mhwasil** [comment]
> IMO this is what semantic versioning should be used for, not the commit hashes.

Okay, I think that's the compromise.
Then we should omit `bitbots` from the image name and add branch/ros dist to the image name, instead of using it as a tag:
what do you think of this?
* `bitbots/industrial-kinetic:{tag/release}`
* `bitbots/domestic-kinetic:{tag/release}`
* `bitbots/base-kinetic:{tag/release}` --> tag here can be `latest` since there is not many changes in here

**Comment by argenos** [comment]
Yeah, I think as long as @alex-mitrevski and @sthoduka agree to it. Making changes to the naming convention means updating the CI across repos, and I'm not sure who would take over the athome one (or if they're ok with it).

**Comment by argenos** [comment]
Adding here what I mentioned in Slack: 

@mhwasil https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
Travis introduced some pricing changes for public repositories too. Might be worth it to build the docker images in GitHub and just run tests or whatever in the CI if you plan to use it extensively
